build:
  tags: building
  stage: build
  script: 

    - echo "Full build of the current dev statges."

test_unit:
  tags: testing
  stage: test
  script: 
    
    - echo "Once all builds in build stage complete,"
    - echo "Start unit test after succefull build."

test_integration:
  tags: testing
  stage: test
  script: 

    - echo "Once unit tests complete,"
