- name: Install apt HTTPS and GPG keys dependencies
  become: yes
  apt:
    update_cache: yes
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
