- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add apt repository for latest docker
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
- name: Install docker
  become: yes
  apt:
    update_cache: yes
    package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
